<%@ Page Language="vb" AutoEventWireup="false" Codebehind="Activities.aspx.vb" Inherits="HealthDiary.Activities"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
  <head>
    <title>Activities</title>
    <meta name="GENERATOR" content="Microsoft Visual Studio .NET 7.1">
    <meta name="CODE_LANGUAGE" content="Visual Basic .NET 7.1">
    <meta name=vs_defaultClientScript content="JavaScript">
    <meta name=vs_targetSchema content="http://schemas.microsoft.com/intellisense/ie5">
  </head>
  <body MS_POSITIONING="GridLayout">

    <form id="Form1" method="post" runat="server">
<table width="80%" align="center" class="FlatContainer" align="center" cellpadding="0" cellspacing="8">
<tr>
	<td align="left" style="FONT-SIZE: 10pt;COLOR: #191970;LINE-HEIGHT: 14pt;FONT-FAMILY: sans-serif"> 
	<img src="activities.gif" width="100%">
<ul>
<li><b>Ball Throwing</b><br>            Ball throwing could include tossing the ball (baseball, weighted ball, volleyball) to another person, or in a team, or just by yourself off a wall.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Ballet </b>Ballet could include participating in a dance or theatre class, event, or just practicing by yourself in front of a mirror.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Basketball </b><br>            Basketball could include playing on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Berry Picking </b><br>            Berry Picking could include going by yourself or others out to pick berries in the woods, tundra, on a farm, or just walking.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Bicycling</b><br>            Bicycling could include going by yourself on a trail, highway, around the neighborhood, or participating in an event or race.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Birding </b><br>            Birding could include going by yourself on a trail, on a trail, around the neighborhood, or participating in an event or activity with others to identify birds.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Baseball </b><br>            Baseball could include playing on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Calistenics </b><br>            Calistenics could include participating in a class, by yourself at a specific place in your home, with friends, or even with a video.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Cheerleading </b><br>            Cheerleading could include playing on a team, or just with friends in the neighborhood, or even by yourself in your home, or with music.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Climbing </b><br>            Climbing could include going with a team, or just with friends in the neighborhood, visiting a climbing gym, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Dancing</b><br>            Dancing could include choreography on a team, or just with friends in the neighborhood, or even by yourself at home to music.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Dog sledding </b><br>            Dog sledding could include participating with a team of people, or just with friends in the neighborhood, racing in an event, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Ice Skating </b><br>            Ice skating could include being part of a team, or just with friends in the neighborhood, at a rink, in a competition, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Fishing </b><br>            Fishing could include fly fishing with friends or alone, going out in a boat or hiking to a lake or stream.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Geo Games </b><br>            Geo games include finding a stashed treasure that has a radio beacon you track down by a global position system (GPS).  You could participate on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Gymnastics </b><br>            Gymnastics could include playing on a team, competing in an event, with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Hiking</b><br>            Hiking could include participating on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Hunting </b><br>            Hunting could include participating on a team, or just with friends in the neighborhood, or even by yourself in the woods.  Be sure to observe safety and regulations wherever you hunt.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Jumping Rope </b><br>            Jumping rope could include participating on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Kayaking </b><br>            Kayaking could include competition as a team, going with friends, or just paddling around by yourself.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Martial Arts </b><br>            Martial Arts could include participating in a sponsored event, competition, as a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Recreational Vehicles </b><br>            Recreational vehicles could include going out by yourself or with others to snow machine, 4-wheel or ride around with some challenges that get you moving and your heart rate up.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Roller Blading </b><br>            Rollerblading could include participating on a team, visiting a gym or skate park with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Running</b><br>            Running could include participating on a team, competing in an event, with friends or yourself indoors or outdoors.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Skateboarding</b><br>            Skateboarding could include participating on a team, visiting a gym or skate park with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Skiing</b><br>            Skiing could include participating on a team, competing in an event, with friends or yourself indoors or outdoors.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Sledding</b><br>            Sledding could include participating on a team, competing in an event, with friends or yourself indoors or outdoors.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Snowboarding</b><br>            Snowboarding could include participating on a team, competing in an event, with friends or yourself outdoors or at a ski area. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Soccer </b><br>            Soccer could include playing on a team, or just with friends in the neighborhood, or even by yourself in the back yard.  The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.</b><br>            </b><li><b>Surfing </b><br>            Surfing could include participating on a team, competing in an event, with friends or yourself anywhere the surf is up. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Swimming </b><br>            Swimming could include participating on a team, competing in an event, with friends or yourself indoors in a pool, or outdoors in a pool, river, ocean, lake. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.</b><li><b>Swinging</b><br>            Swinging could include participating on a team, competing in an event, with friends or yourself outdoors whever there’s a swing to play on. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Tennis </b><br>            Tennis could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever there’s a court. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Volleyball </b><br>            Volleyball could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever there’s a place to play with a net. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Walking</b><br>            Walking could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever you can stretch your legs. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Weight Lifting </b><br>            Weight lifting could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever there’s weights to lift.  You could be creative and lift objects that are weighted (like a can of soup) or get as technical as tracking each specific weight, which part of the body you are focusing on and repetitions. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Wrestling </b><br>            Wrestling could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever there’s a place to get active. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Yoga </b><br>            Yoga could include participating on a team, competing in an event, with friends or yourself indoors or outdoors wherever you feel comfortable and relaxed. The object is to have movement from all parts of your body, getting the heart to increase to 80% for a minimum of 20 minutes.
<br><br></li><li><b>Other </b><br>            We would like to hear your suggestions for other activities.  If you are participating in something not already listed, please let us know:  roxy@gci.net</b>
</ul>
</div>
<img src="activities.gif" width="100%">
</td></tr></table>
    </form>

  </body>
</html>
